# Render.com 배포 설정 파일
# https://render.com/docs/blueprint-spec

services:
  - type: web
    name: ctr-aiops-backend
    env: python
    region: singapore
    plan: free
    branch: main
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /api/health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false  # Render Dashboard에서 수동으로 추가
    autoDeploy: true

